apiVersion: v1
kind: Service
metadata:
  name: prometheus-svc
  labels:
    env: prometheus
spec:
  ports:
    - port: 9090
  selector:
    env: prometheus
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pv-claim
  labels:
    env: prometheus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: prometheus-deployment
  labels:
    env: prometheus
spec:
  selector:
    matchLabels:
      env: prometheus
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        env: prometheus
    spec:
      containers:
      - image: prom/prometheus:latest
        name: prometheus
        ports:
        - containerPort: 9090
          name: prometheus
        volumeMounts:
        - name: prometheus-persistent-storage
          mountPath: /etc/prometheus/data
      volumes:
      - name: prometheus-persistent-storage
        persistentVolumeClaim:
          claimName: prometheus-pv-claim